apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: null
  generation: 1
  labels:
    run: nodedocker-web
  name: nodedocker-web
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nodedocker-web
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nodedocker-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nodedocker-web
    spec:
      containers:
      - image: gcr.io/testproject-garrett/nodedocker:v6
        imagePullPolicy: Always
        name: nodedocker-web
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
